[package]
  name = "imprintor"
  version = "0.1.0"
  authors = []
  edition = "2021"

[lib]
  name = "imprintor"
  crate-type = ["cdylib"]

[dependencies]
  rustler = "0.36.2"
  typst = "0.11.1"
  typst-pdf = "0.11.1"
  fontdb = "0.18.0"
  comemo = "0.4"
